name: run web test in github actions

on: [workflow_dispatch]
jobs:
  run-web-test:
    runs-on: ubuntu-latest

    steps:
      - name: pull the project in to the runner
        uses: actions/checkout@v4

      - name: set up java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'

     
      - name: run the web test
        run:
          mvn clean test
      
